### ISSUE TITLE
Cannot run with macOS

### ISSUE THREAD

**Issue by HTsuruo** [mulaRahul/keyviz#171]
**Describe the bug**

Run this command for running with macos

```
flutter run -d macos
```

And then, output is here.

```sh
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot add to an unmodifiable list
#0      UnmodifiableListMixin.add (dart:_internal/list.dart:114:5)
#1      KeyEventProvider._registerMouseListener (package:keyviz/providers/key_event.dart:282:15)
#2      KeyEventProvider._init (package:keyviz/providers/key_event.dart:269:5)
<asynchronous suspension>
```

**Version**: v2.0.0a

**To Reproduce**
1. Checkout branch to `v2.0.0a`
2. Changed minimun target version `10.14` to `10.15` because following error occurs.

```
/keyviz/macos/Flutter/GeneratedPluginRegistrant.swift:9:8: error: compiling for macOS 10.14, but module 'macos_window_utils' has a minimum deployment target of macOS 10.14.6: /keyviz/build/macos/Build/Products/Debug/macos_window_utils/macos_window_utils.framework/Modules/macos_window_utils.swiftmodule/arm64-apple-macos.swiftmodule
import macos_window_utils
```

3. `flutter run -d macos`

**Expected behavior**
Works fine this application with macOS.

**Screenshots**
Freezed.
<img width="813" alt="image" src="https://github.com/mulaRahul/keyviz/assets/12729025/3884d671-0b4c-4b89-9483-62f1514815e2">

**Desktop (please complete the following information):**
 - MacBook Pro M1(Apple Silicon)
 - macOS: Ventura 13.4.1

**Comment by mulaRahul** [comment]
Have you given permissions for input monitoring and accessibility **Settings > Privacy & Security > Input Monitoring/Accessibility** to keyviz (debug) and the terminal/vs code (where running `flutter run` command)?

**Comment by HTsuruo** [comment]
@mulaRahul 

Thanks for your reply.

> Have you given permissions for input monitoring and accessibility Settings > Privacy & Security > Input Monitoring/Accessibility to keyviz (debug)

Yes.  I added **Input Monitoring/Accessibility** permission to  `keyvz > build > macos > Build > Products > Debug > keyviz.app`. 

I tried `flutter run` with VS Code.

**Comment by mulaRahul** [comment]
You need to provide the permissions to VS Code as well, because technically where the app is running.

**Comment by mulaRahul** [comment]
Can you see any changes with [v2.0.0a2](https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a2)?

**Comment by htsuruo** [comment]
@mulaRahul 

Thank you for great work.

I just tried running with tag [`v2.0.0a2`](https://github.com/mulaRahul/keyviz/tree/v2.0.0a2)  as your comment. Unfortunately, the issue still occurred.

**Comment by mulaRahul** [comment]
Can you share logs/output like above?

**Comment by htsuruo** [comment]
@mulaRahul 

Apologize for late response.
Here is all of logs.

>Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-001271510A41801E }
{ platform:macOS, arch:x86_64, id:00006001-001271510A41801E }
2024-05-03 22:18:12.367 keyviz[29568:56797777] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Connecting to VM Service at ws://127.0.0.1:62701/2f-3bCO3MLA=/ws
flutter: Failed to initialize listener backend
flutter: couldn't register mouse listener
flutter: cannot register keyboard listener!

**Comment by mulaRahul** [comment]
Have given the above permissions?

**Comment by dnet5** [comment]
Same stuff here. I was on a previous version (dunno which one, unfortunately) that was running just fine. But now, even giving the permissions on accessibility and input, the error keeps showing.

I don't have flutter installed, and never had. So, I don't know if that's the problem, once the old version was running just fine.

**Comment by foong** [comment]
same issue with me
Im on M3 Sonoma

**Comment by m-muaz** [comment]
I am on MacOS Sequoia v15.0. I cannot run the application though I have given the application input monitoring permission. 

<img width="1174" alt="image" src="https://github.com/user-attachments/assets/08ae4216-105f-40a6-80d9-cad695675804">

**Comment by MicroSharpAnt** [comment]
> 我使用的是 MacOS Sequoia v15.0。尽管我已授予应用程序输入监控权限，但我无法运行该应用程序。
> 
> <img alt="图像" width="1174" src="https://private-user-images.githubusercontent.com/85618702/369552224-08ae4216-105f-40a6-80d9-cad695675804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDA5MDksIm5iZiI6MTczMTk0MDYwOSwicGF0aCI6Ii84NTYxODcwMi8zNjk1NTIyMjQtMDhhZTQyMTYtMTA1Zi00MGE2LTgwZDktY2FkNjk1Njc1ODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE0MzY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNzRkYmMxM2E1MDg3ZWQ1MjlmMWNjNWQ3MTMyZTU1MWNhYWM2Y2FjZTQ0NzlmOWZhMTA5Y2RmN2JkY2Q3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KImNh7EMMo8dPjihIZ9KkQc9mw_28PWRYabRCOSXJ5Y">

In fact, you don't need to grant the program input monitoring rights, just turn on the app's switch in the accessibility function.

**Comment by lxb1226** [comment]
Ensure that the permissions for **Privacy & Security > Accessibility and Privacy & Security > Input Monitoring** are granted. Note that there are two separate permissions you need to enable: one for Accessibility and one for Input Monitoring.
