### ISSUE TITLE
MissingPlugin

### ISSUE THREAD

**Issue by Callemul** [mulaRahul/keyviz#319]
**Describe the bug**

**Version**: v2.0.0-alpha2

**To Reproduce**
0. Install `sudo apt-get install libayatana-appindicator3-dev`
1. Go to keyviz folder
2. Run with terminal
3. Errors and black screen (and I see hotkeys, but at separate black "window". 

**Screenshots**
![image](https://github.com/user-attachments/assets/beae03c2-eeb3-4477-accf-c8b6f73a3fd1)
![image](https://github.com/user-attachments/assets/92a28a3a-2b23-427f-82a0-26f9434e3bb1)
![image](https://github.com/user-attachments/assets/3bf83ecc-bf2e-428a-bb93-f06bb3bc91b9)

**Desktop (please complete the following information):**
 - Linux Mint 22

**Additional context**

`ivanov@PC0CompRoom:~/Documents/keyviz_$ ./keyviz 
flutter: registered mouse listener
flutter: keyboard listener registered
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setIgnoreMouseEvents on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      WindowManager.setIgnoreMouseEvents (package:window_manager/src/window_manager.dart:699)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setHasShadow on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      WindowManager.setHasShadow (package:window_manager/src/window_manager.dart:667)
<asynchronous suspension>
`

**Comment by sbeyer** [comment]
I can second that. After I got it to compile under Linux (Fedora Workstation 41), I get:
```
$ flutter run --release
Launching lib/main.dart on Linux in release mode...
Building Linux application...                                           
✓ Built build/linux/x64/release/bundle/keyviz

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
flutter: [ json:load ]: File: '/home/sbeyer/Documents/config.json' not found!
flutter: registered mouse listener
flutter: keyboard listener registered
flutter: [ json:load ]: File: '/home/sbeyer/Documents/style.json' not found!
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method setIgnoreMouseEvents on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      WindowManager.setIgnoreMouseEvents (package:window_manager/src/window_manager.dart:699)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method setHasShadow on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      WindowManager.setHasShadow (package:window_manager/src/window_manager.dart:667)
<asynchronous suspension>


(keyviz:15257): Gtk-CRITICAL **: 15:06:24.638: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

and a black fullscreen window. If invoked with `--debug`, I get a black fullscreen window with a `debug` badge.

**Comment by conventoangelo** [comment]
https://github.com/mulaRahul/keyviz/issues/280#issuecomment-2844225153
