### ISSUE TITLE
[BUG] The window will be black and block my screen.

### ISSUE THREAD

**Issue by Miuzarte** [mulaRahul/keyviz#43]
**Describe the bug**
The window will be black and block my screen but not always. It flickings between normal(transparent) and black quickly when I press keys.

**Version**: v1.0.6

**To Reproduce**
1. Just run the program

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/66856838/187658225-0c3c64ec-774c-4cb7-9f5e-c91e05258c83.png)
![QMF{0@@8 97{R2XFZ{WT6(2](https://user-images.githubusercontent.com/66856838/187658965-864ae8fe-4b62-4439-9828-9eca3335f68e.png)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by Miuzarte** [comment]
> Can you share more specifications of your system like windows **build number**?

![image](https://user-images.githubusercontent.com/66856838/187857892-fcf5759b-3339-4cfc-a503-af2f8f0a5db3.png)
版本	Windows 10 IoT 企业版 LTSC
版本号	21H2
安装日期	‎2022/‎07/‎31 ‎周日
操作系统内部版本	19044.1889
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by MatrixFr** [comment]
same problem on window 7... 
impossible to use your app :'(

**Comment by mulaRahul** [comment]
> same problem on window 7... impossible to use your app :'(

The transparent windows effect is only supported on Windows 10 1803 or above. That's why you're seeing the black screen.

**Comment by mulaRahul** [comment]
Hello @Miuzarte, can you reproduce the same with https://github.com/mulaRahul/keyviz/releases/tag/v2.0.0a?

**Comment by Miuzarte** [comment]
sry I missed this email notification.

In this version there is no more flicker, BUT now it only reacts when I am pressing `Ctrl`, `Alt` or `WIN`.
Normally it can't capture my any input, even run it as administrator.
The right side of the screen is an input capture program written in Python.
![Cp9xdDOfQA](https://github.com/mulaRahul/keyviz/assets/66856838/8dbfde8e-e33f-4552-821f-06ae98d2dcf1)

and my environment: 
![image](https://github.com/mulaRahul/keyviz/assets/66856838/2d773a54-00a4-4915-b9d4-0be18c210ced)
版本	Windows 10 IoT 企业版 LTSC
版本号	21H2
安装日期	‎2022/‎7/‎31 ‎周日
操作系统内部版本	19044.3208
体验	Windows Feature Experience Pack 1000.19041.1000.0


I can help more if you need because I'm currently in the summer vacation, but it may not be very timely.

**Comment by mulaRahul** [comment]
Thanks for the feedback!

**Comment by HowcanoeWang** [comment]
Got the same problem on the manjaro kde plasma (the latest version from AUR source)

instead of the half screen, the full screen has been covered and could do nothing except forcing restart computer

**Comment by xbelanch** [comment]
Got the same issue on Arch Linux: full black screen:
```
home-X99F8:~/Sources/keyviz_v2.0.0a_linux_x64$ ./keyviz 

(keyviz:13060): Gdk-CRITICAL **: 19:36:51.463: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: [ json:load ]: File: '/home/rotter/Documents/config.json' not found!
flutter: registered mouse listener
flutter: keyboard listener registered
flutter: [ json:load ]: File: '/home/rotter/Documents/style.json' not found!
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setIgnoreMouseEvents on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
<asynchronous suspension>
#1      WindowManager.setIgnoreMouseEvents (package:window_manager/src/window_manager.dart:697)
<asynchronous suspension>
#2      _initWindow.<anonymous closure> (package:keyviz/main.dart:36)
<asynchronous suspension>


(keyviz:13060): Gdk-CRITICAL **: 19:36:51.789: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
flutter: keyboardEvents: {371805: {8589934848: ⬇️[control](🟢)}}

```

**Comment by GWDx** [comment]
In Linux, removing `gtk_widget_show(GTK_WIDGET(window));` and `gtk_widget_show(GTK_WIDGET(view));` from `linux/my_application.cc` can solve the black screen issue and make the background transparent. Refer to the [flutter_acrylic commit](https://github.com/alexmercerind/flutter_acrylic/commit/77b641a6033e114a116a8777762d227040eceed5#diff-e98abc259949baf8be20747542aaf9087967cb1aacaf68616bf42baaac35f74cL52).

However, I encountered a bug where mouse clicks cannot be passed through.

OS: Debian bookworm
DE: Plasma 5.27
